### ISSUE TITLE
Bad Linkage errors

### ISSUE THREAD

**Issue by OlivierJourdan** [vipm-io/caraya#192]
This is more of a support request than an issue report. I'm sorry if this is the wrong place to do that.

I use Caraya most simply. All my tests only use those two VIs 👇 

<img width="345" alt="image" src="https://github.com/user-attachments/assets/2b0855ef-f9b3-48e4-9dca-e99edf5c9903">

It's been working fine for ages. But when I'm running tests with CLI using this vI 👇 

<img width="142" alt="image" src="https://github.com/user-attachments/assets/6cc800f2-143e-47f6-9cc6-3b828d2468d6">

I'm coming across bad linkage errors I can't explain.

I have two similar projects (2 plug-ins). One is correctly tested, and the second is sending me a "bad linkage" issue pointing out an existing VI…

Do you have any idea what's going on?

**Comment by francois-normandin** [comment]
@OlivierJourdan 

I do not know of all the ways you could get this error message, but bad linkage errors are usually something in the dependencies of the VI that is missing. If your VI is not broken, could it be that it contains a disable structure that references a deleted or uninstalled library/VI?

**Comment by OlivierJourdan** [comment]
Sorry for the late reply (and thanks for your input, @francois-normandin ).

I finally found out why I had a different behavior running in my LV environment or my CI. In the CI, the code wasn't loaded in the project environment. This messes up some relative paths in the code, causing a DLL not to load correctly.

I'm relieved the issue was on my side.
The issue can be closed.
